#spring:
#  application:
#    name: testLogin
spring:
  token:
    secret: m#MySecret5339T
    issuer: BackendService
  email:
    from: YOUR_ACCOUNT@gmail.com #spxth5735
---
spring:
  profiles:
    active:
      - dev
---

server:
  port: 1150
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: Tonpostgresql04
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: "my-awesome-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_USERNAME #spxth5735
    password: YOUR_PASSWORD #gkdpamanfwkfqpia
    properties:
      mail :
        smtp:
          auth: true
          starttls:
            enable: true